CREATE VIEW VIEW_USER_INFORMATION 
(USER_ID, FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH,
DAY_OF_BIRTH, GENDER, CURRENT_CITY, CURRENT_STATE, CURRENT_COUNTRY,
HOMETOWN_CITY, HOMETOWN_STATE, HOMETOWN_COUNTRY, INSTITUTION_NAME,
PROGRAM_YEAR, PROGRAM_CONCENTRATION, PROGRAM_DEGREE)
AS
	SELECT DISTINCT U.USER_ID, U.FIRST_NAME, 
	U.LAST_NAME, U.YEAR_OF_BIRTH, U.MONTH_OF_BIRTH,
	U.DAY_OF_BIRTH, U.GENDER, CC.CITY_NAME, CC.STATE_NAME, 
	CC.COUNTRY_NAME, HT.CITY_NAME, HT.STATE_NAME,
	HT.COUNTRY_NAME, P.INSTITUTION, P.CONCENTRATION, P.DEGREE)
	FROM USERS U, CITIES CC, USER_CURRENT_CITY UCC, CITIES HT,
	USER_HOMETOWN_CITY UHC, PROGRAMS P, EDUCATION E
	WHERE U.USER_ID=UCC.USER_ID AND U.USER_ID=UHC.USER_ID AND
	CC.CITY_ID=UCC.CURRENT_CITY_ID AND HT.CITY_ID=UHC.HOMETOWN_CITY_ID
	AND E.USER_ID=U.USER_ID AND E.PROGRAM_ID=P.PROGRAM_ID;

CREATE VIEW VIEW_ARE_FRIENDS (USER1_ID, USER2_ID)
AS
	SELECT USER1_ID, USER2_ID FROM FRIENDS;

CREATE VIEW VIEW_PHOTO_INFORMATION
(ALBUM_ID, OWNER_ID, COVER_PHOTO_ID, ALBUM_NAME, ALBUM_CREATED_TIME,
ALBUM_MODIFIED_TIME, ALBUM_LINK, ALBUM_VISIBILITY, PHOTO_ID, 
PHOTO_CAPTION, PHOTO_CREATED_TIME, PHOTO_MODIFIED_TIME, PHOTO_LINK)
AS
	SELECT DISTINCT A.ALBUM_ID, A.ALBUM_OWNER_ID, A.COVER_PHOTO_ID,
	A.ALBUM_NAME, A.ALBUM_CREATED_TIME, A.ALBUM_MODIFIED_TIME,
	A.ALBUM_LINK, A.ALBUM_VISIBILITY, P.PHOTO_ID, P.PHOTO_CAPTION,
	P.PHOTO_CREATED_TIME, P.PHOTO_MODIFIED_TIME, P.PHOTO_LINK
	FROM ALBUMS A, PHOTOS P
	WHERE A.ALBUM_ID = P.ALBUM_ID;

CREATE VIEW VIEW_TAG_INFORMATION
(PHOTO_ID, TAG_SUBJECT_ID, TAG_CREATED_TIME, TAG_X_COORDINATE, TAG_Y_COORDINATE)
AS
	SELECT DISTINCT TAG_PHOTO_ID, TAG_SUBJECT_ID, TAG_CREATED_TIME, TAG_X, TAG_Y
	FROM TAGS T;

CREATE VIEW VIEW_EVENT_INFORMATION
(EVENT_ID, EVENT_CREATOR_ID, EVENT_NAME, EVENT_TAGLINE, 
EVENT_DESCRIPTION, EVENT_HOST, EVENT_TYPE, EVENT_SUBTYPE,
EVENT_ADDRESS, EVENT_CITY, EVENT_STATE, EVENT_COUNTRY, 
EVENT_START_TIME, EVENT_END_TIME)
AS
	SELECT DISTINCT E.EVENT_ID, E.EVENT_CREATOR_ID, E.EVENT_NAME,
	E.EVENT_TAGLINE, E.EVENT_DESCRIPTION, E.EVENT_HOST, E.EVENT_TYPE,
	E.EVENT_SUBTYPE, E.EVENT_ADDRESS, C.CITY_NAME, C.STATE_NAME, 
	C.COUNTRY_NAME, E.EVENT_START_TIME, E.EVENT_END_TIME
	FROM USER_EVENTS E, CITIES C
	WHERE E.EVENT_CITY_ID = C.CITY_ID