DROP TABLE USERS;

DROP TABLE FRIENDS;
DROP TRIGGER EXISTEDFRIENDSHIP;

DROP TABLE CITIES;
DROP TABLE USER_CURRENT_CITY;
DROP TABLE USER_HOMETOWN_CITY;
DROP TABLE MESSAGES;
DROP TABLE PROGRAMS;
DROP TABLE EDUCATION;
DROP TABLE USER_EVENTS;
DROP TABLE PARTICIPANTS;

ALTER TABLE ALBUMS DROP CONSTRAINT COVER_CONSTRAINT;

DROP TABLE ALBUMS;
DROP TABLE PHOTOS;
DROP TABLE TAGS;